name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: stable-linux
            container: debian:bookworm
          - name: latest-linux
            container: ubuntu:latest
          - name: macos
            platform: macos-latest
          - name: windows
            platform: windows-latest

    runs-on: ${{ matrix.platform || 'ubuntu-latest' }}
    container: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v4

      - name: Prepare dependencies (Linux)
        if: matrix.container != ''
        run: |
          apt-get update
          apt-get install -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './app/src-tauri -> target'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: app/package-lock.json

      - name: Install frontend deps
        run: npm ci
        working-directory: app

      - name: Build and release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPIMAGE_EXTRACT_AND_RUN: 1
        with:
          projectPath: app
          tagName: v__VERSION__
          releaseName: v__VERSION__
          releaseDraft: true
          prerelease: false
