name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies (for Tauri 2.0)
      run: |
        sudo apt-get update &&
        sudo apt-get install -y \
          libwebkit2gtk-4.1-dev \
          libjavascriptcoregtk-4.1-dev \
          libgtk-3-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev
    
    - name: Build
      run: cargo build --verbose
      working-directory: app/src-tauri
    
    - name: Run tests
      run: cargo test --verbose
      working-directory: app/src-tauri
